# Generated by Django 5.2.13 on 2026-04-18 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('spo2', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=15)),
                ('respiratory_rate', models.PositiveIntegerField()),
                ('temperature', models.FloatField()),
                ('urea', models.FloatField()),
                ('ph', models.FloatField()),
                ('wbc_count', models.FloatField()),
                ('confusion', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'clinical_data',
            },
        ),
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xray_image', models.ImageField(upload_to='xrays/')),
                ('severity_score', models.FloatField(blank=True, null=True)),
                ('risk_class', models.CharField(blank=True, choices=[('I', 'Class I'), ('II', 'Class II'), ('III', 'Class III'), ('IV', 'Class IV'), ('V', 'Class V')], max_length=3, null=True)),
                ('heatmap_path', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='cases.clinicaldata')),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='patient_cas_status_fb0809_idx'), models.Index(fields=['patient', '-created_at'], name='patient_cas_patient_a30867_idx')],
            },
        ),
    ]
