"""Summary builder — composes factual content from case + clinical + AI output.

No clinical recommendations or thresholds. Summaries echo stored values only.
"""

from __future__ import annotations

from typing import TypedDict


class ReportContent(TypedDict):
    simplified_text: str
    medication_instructions: str


PLACEHOLDER_MEDS = (
    "[Placeholder] Medication instructions will be generated by the "
    "simplification service in Phase 12. Clinician review required."
)


def build_content(case) -> ReportContent:
    """Compose the textual body of a summary for a given PatientCase."""
    patient = case.patient
    cd = case.clinical_data

    diag_pct = (
        f"{case.diag_probability * 100:.1f}%"
        if case.diag_probability is not None
        else "N/A"
    )
    sev_pct = (
        f"{case.severity_probability * 100:.1f}%"
        if case.severity_probability is not None
        else "N/A"
    )

    if case.has_pneumonia is True:
        diagnosis_summary = (
            f"Pneumonia detected (probability {diag_pct}). "
            f"Severity classification: {'Severe' if case.is_severe else 'Non-severe'} "
            f"(severity probability {sev_pct})."
        )
    elif case.has_pneumonia is False:
        diagnosis_summary = f"No pneumonia detected (probability {diag_pct})."
    else:
        diagnosis_summary = "Diagnosis not yet available."

    temp_c = (
        f"{(cd.temp_fahrenheit - 32) * 5 / 9:.1f}°C / {cd.temp_fahrenheit:.1f}°F"
        if cd.temp_fahrenheit is not None
        else "N/A"
    )

    simplified = (
        f"Case Record — Case #{case.id}\n"
        f"Patient: {patient.full_name} (National ID {patient.national_id})\n"
        f"Age {cd.age}, {patient.get_gender_display()}\n"
        f"Seen by: {case.clinician.name or case.clinician.email}\n"
        f"Date: {case.created_at:%Y-%m-%d %H:%M}\n\n"
        f"AI-Assisted Diagnosis: {diagnosis_summary}\n"
        f"Model: DenseNet121 Multi-Task (MIMIC-CXR training set)\n\n"
        f"Recorded vitals:\n"
        f"  SpO2: {cd.spo2}%\n"
        f"  Heart Rate: {cd.hr} bpm\n"
        f"  Respiratory Rate: {cd.rr} breaths/min\n"
        f"  Systolic BP: {cd.sys_bp} mmHg\n"
        f"  Temperature: {temp_c}\n"
        f"  BUN: {cd.bun} mg/dL\n"
        f"  GCS Total: {cd.gcs_total}\n\n"
        f"[Placeholder] A clinician-facing plain-language summary will be "
        f"generated by the simplification service in Phase 12. "
        f"Clinician review required."
    )

    return {
        "simplified_text": simplified,
        "medication_instructions": PLACEHOLDER_MEDS,
    }
