"""Report builder — composes factual content from case + clinical + AI output.

No clinical recommendations or thresholds are emitted here; a real
simplification/medication service (Phase 12) will produce the narrative.
This module only echoes stored values and flags the parts that need
clinician review.
"""
from __future__ import annotations

from typing import TypedDict


class ReportContent(TypedDict):
    simplified_text: str
    medication_instructions: str


PLACEHOLDER_MEDS = (
    "[Placeholder] Medication instructions will be generated by the "
    "simplification service in Phase 12. Clinician review required."
)


def build_content(case) -> ReportContent:
    """Compose the textual body of a report for a given PatientCase.

    The summary only echoes recorded values — no interpretation,
    no thresholds, no treatment guidance.
    """
    patient = case.patient
    cd = case.clinical_data
    risk = case.risk_class or "N/A"
    severity = (
        f"{case.severity_score:.2f}" if case.severity_score is not None else "N/A"
    )
    confidence = (
        f"{case.confidence_score:.2f}" if case.confidence_score is not None else "N/A"
    )

    simplified = (
        f"Case Record — Case #{case.id}\n"
        f"Patient: {patient.full_name} (National ID {patient.national_id})\n"
        f"Age {cd.age}, {patient.get_gender_display()}\n"
        f"Seen by: {case.clinician.name or case.clinician.email}\n"
        f"Date: {case.created_at:%Y-%m-%d %H:%M}\n\n"
        f"AI-assisted output: Risk Class {risk}, severity score {severity}, "
        f"confidence {confidence}.\n\n"
        f"Recorded vitals: SpO2 {cd.spo2}%, BP {cd.blood_pressure} mmHg, "
        f"RR {cd.respiratory_rate}, Temp {cd.temperature} C.\n"
        f"Recorded labs: urea {cd.urea}, pH {cd.ph}, WBC {cd.wbc_count}. "
        f"CURB-65 confusion flag: {'Yes' if cd.confusion else 'No'}.\n\n"
        f"[Placeholder] A clinician-facing plain-language summary will be "
        f"generated by the simplification service in Phase 12. "
        f"Clinician review required."
    )

    return {
        "simplified_text": simplified,
        "medication_instructions": PLACEHOLDER_MEDS,
    }
