# Generated by Django 5.2.13 on 2026-04-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplified_text', models.TextField()),
                ('medication_instructions', models.TextField()),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV')], default='PDF', max_length=3)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('patient_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='cases.patientcase')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
