# Generated by Django 5.2.13 on 2026-04-18 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('CLINICIAN', 'Clinician'), ('BOT', 'Bot')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='cases.patientcase')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['patient_case', 'timestamp'], name='chat_messag_patient_0a4d41_idx')],
            },
        ),
    ]
